[package]
name = "mejiro-search"
version = "0.1.0"
description = "A WASM search for blog posts"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsugumi-sys/mejiro" 
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2.100"
