[package]
name = "mejiro-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
config = { path = "../config" }
html = { path = "../html" }
rand = "0.9.1"
serde_yaml = "0.9.34"
