name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install rust toolchains
      run: |
        rustup component add clippy
        rustup component add rustfmt

    - name: Install typos
      run: |
        if ! command -v typos &> /dev/null; then
          cargo install typos-cli
        else
          echo "typos is already installed."
        fi

    - name: Run typos
      run: typos

    - name: Check code format
      run: cargo fmt --all -- --check

    - name: Lint with clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    # - name: Build in release mode
    #   run: cargo build --workspace --release

    # - name: Run tests
    #   run: cargo test --workspace --release

